apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: todo
data:
  POSTGRES_DB: "tododb"
  POSTGRES_USER: "todo"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
