apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: todo
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: todo
spec:
  replicas: 1
  selector: { matchLabels: { app: db } }
  template:
    metadata: { labels: { app: db } }
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        env:
        - name: POSTGRES_DB
          valueFrom: { configMapKeyRef: { name: app-config, key: POSTGRES_DB } }
        - name: POSTGRES_USER
          valueFrom: { configMapKeyRef: { name: app-config, key: POSTGRES_USER } }
        - name: POSTGRES_PASSWORD
          valueFrom: { secretKeyRef: { name: db-secret, key: POSTGRES_PASSWORD } }
        ports: [{containerPort: 5432}]
        volumeMounts:
        - name: dbdata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: dbdata
        persistentVolumeClaim:
          claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: todo
spec:
  type: ClusterIP
  selector: { app: db }
  ports:
  - port: 5432
    targetPort: 5432
